### PR TITLE
fix: double click event handling

### PR DESCRIPTION
**Pull request by tpoisseau**
DOM `pointerdown` and `pointerup` do not contain number of click in `detail` like `click` events.

So I tweak `GenericEditorArea.eventHappened` to call `handleDoubleClick` on `GenericMouseEvent.MOUSE_CLICKED`

Closes: https://github.com/cheminfo/openchemlib-js/issues/225

### CODE REVIEW

**Comment by tpoisseau** [comment]
@targos Do you confirm I must PR https://github.com/Actelion/openchemlib for java changes ?

**Comment by targos** [comment]
> @targos Do you confirm I must PR [Actelion/openchemlib](https://github.com/Actelion/openchemlib) for java changes ?

Yes

**Comment by targos** [comment]
Update of OCL in https://github.com/cheminfo/openchemlib-js/pull/233 fixed the issue according to my tests on the cloudflare preview.

**Comment by tpoisseau** [comment]
Ok, I updated openchemlib submodule. Seems works as expected.
I let you approve @targos before I merge

**Comment by targos** [comment]
But I already updated the submodule in https://github.com/cheminfo/openchemlib-js/pull/233

**Comment by tpoisseau** [comment]
Yes, So I just merged and added comment (so we don't think it's missing).

This PR remove `event.detail` on `clickCount` argument.

**Review by targos — APPROVED** [review]

**Pull request merged**
